### ISSUE TITLE
Send more than one mapping to the table name position

### ISSUE THREAD

**Issue by manuelma** [Spine-project/Spine-Database-API#123]
And concatenate the names using "_" for instance, in order to compose the table name. This is required by the old export to excel where one wants the class name and the parameter type to be in the table name.

Also, data in each table should only be filtered by the mappings that go into the table name. At the moment is filtered by the entire upwards hierarchy, which means we end up with a lot of very small tables. Eg.

object class mapping -> some column
object mapping -> some column
parameter mapping -> table name
alternative mapping -> first row
value mapping ->pivoted data

In the above example, we'll have one table per object class, object, and parameter. Whereas I propose we have one table per parameter, because it's only the parameter that's going into the table name.

**Comment by soininen** [comment]
There is the option to set a mapping as 'ignorable' which sets the filtering off. Maybe that would help here?

**Comment by manuelma** [comment]
How does ignorable work? It looks like it only skips update_state if _query doesn't yield any rows?

**Comment by soininen** [comment]
If I remember correctly, it yields the mapping's data if it is available, otherwise it yields None and doesnt' update the state. For example, if a database has two object classes, A and B and only A has parameter P defined, then with mapping

ObjectClassMapping - ParameterDefinitionMapping(ignorable) - ObjectMapping

you would get

A P object1
...
A P objectN
B None object1
...
B None objectN

**Comment by manuelma** [comment]
Thanks for the explanation!

But what I just did is remove contributions to the 'title_state' from mappings that don't go into the table_name... I hope it's ok, makes a lot more sense to me!
